name: discordIssueMessage

on:
  issues:
    types: [opened]

jobs:
  opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          curl -d "content=*${{ github.actor }} opened submission:* ${{ github.event.issue.title }} **#${{ github.event.issue.number }}**" -X POST ${{ secrets.WEBHOOKURL }}
