name: discordIssueMessage

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          curl -d "content=${{ github.actor }} made a submission: ${{ github.event.issue.name }}${{ github.event.issue.number }}" -X POST ${{ secrets.WEBHOOKURL }}
