name: discordCommitMessage

on:
  push:
    branches: [ "main" ]
  issue_comment:
    types: [created, deleted]    

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          curl -d "content=${{ github.actor }} made a commit: ${{ github.event.head_commit.message }}, ${{ github.ref_name }}" -X POST ${{ secrets.WEBHOOKURL }}
